### ISSUE TITLE
Bug: Normalize both url path and capability substring for endpoint authorization

### ISSUE THREAD

**Issue by denopink** [xmidt-org/bascule#170]
bascule checks wether or not one of the sat token capabilities matches the request url. This works by checking 1) the capabilities like `hooks` is a subset match of the request url and 2) that match starts at index 0:

where `re` is the regex for `hooks` capability and `urlToMatch` should start with `hooks`
https://github.com/xmidt-org/bascule/blob/ef086262e1ebaaabc110a45bf42fbb43ec0f6ea0/basculechecks/endpointchecks.go#L105-L110

The issue at hand is that go's `net` lib may include a leading `/` in its url path. So `urlToMatch` would point to `/hooks` instead of `hooks` and thus failing the endpoint authorization.

The solution is to normalize both `re` and `urlToMatch` to contain a leading `/` such that the currently logic works.

**Comment by JC000** [comment]
The responsibility falls on the creators of the capabilities used in the authorization input to use proper regular expressions to contain word boundaries so that this doesn't happen.

**Comment by denopink** [comment]
@johnabass I don't think we provide a way for a user to configure the regex for comparing these two strings.
Here's the code:
https://github.com/xmidt-org/bascule/blob/ef086262e1ebaaabc110a45bf42fbb43ec0f6ea0/basculechecks/endpointchecks.go#L100-L106

If I'm not missing it and we're actually not supporting that functionality atm, then I can add it.
I believe JC has a good point since other anomalies may show up later.

**Comment by johnabass** [comment]
It's not the regex a user would configure.  It's that custom validators can be written to take advantage of what `bascule` has parsed.

**Comment by denopink** [comment]
closed by #173
