### ISSUE TITLE
bascule allows 'bearer' in token

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/bascule#56]
Bascule accepts tokens with "bearer" or "bEAREr" etc.  The RFC appears to require "Bearer"
https://tools.ietf.org/html/rfc6750#section-2.1
https://tools.ietf.org/html/rfc6750#section-6.1.1

**Comment by kristinaspring** [comment]
bascule can be used for more than basic or bearer auth (such as validating a hashed secret in a header), so I changed the constructor to be case sensitive, so at least we no longer allow this.  To help applications choose to follow the RFC requirements, I also added constants for `Basic` and `Bearer` that applications can use when setting up the bascule middleware.
