### ISSUE TITLE
Add configurable way to Authorize requests without `Authorization` Header  

### ISSUE THREAD

**Issue by joe94** [xmidt-org/bascule#58]
For cases when an Authorization Header value is not provided, bascule to have a configuration flag to allow such request as a no op.

Few notes on potential solutions by @kristinaspring:
> The only thing stopping you from using bascule to allow in devices that don't have Authorization headers is this:
> https://github.com/xmidt-org/bascule/blob/master/basculehttp/constructor.go#L74
> 
> we just have to add a new option in bascule that's basically like a function that's called when the auth header isn't provided and the default is erroring like we do now
> 
> and then we can have another one that's basically just putting an empty Authentication struct in the context with some value for the Authorization, so the enforcer can not fail here:
> https://github.com/xmidt-org/bascule/blob/master/basculehttp/enforcer.go#L47 
> 
> then when setting up the enforcer, add the allow all check for that Authentication's Authorization:
> https://github.com/xmidt-org/bascule/blob/master/checks.go#L18 
> 
> this field
> https://github.com/xmidt-org/bascule/blob/master/context.go#L14
> 

We'll have to make it very clear to clients though about whether a particular request was authorized "legitimately" or due to an allowed no-op.

**Comment by johnabass** [comment]
The redesign has implemented this.
