### ISSUE TITLE
Acquire http client

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/bascule#76]
https://github.com/xmidt-org/bascule/blob/b408708d21bcbdb521594ea846ecb1e1dd4b1771/acquire/auth.go#L49

In addition to providing this `AddAuth()` helper function, we could provide an http.Client that adds the auth to a request before sending it.  [Oauth does this](https://pkg.go.dev/github.com/dghubble/oauth1#Config.Client).

**Comment by johnabass** [comment]
This is a good pattern, but it's better to decorate an interface for this kind of thing.  If you look at the oath's `NewClient` method, that's exactly what it's doing:  it's providing it's own `Transport` implementation that decorates an `http.RoundTripper`.  The returned `http.Client` just uses that transport instance.

Bascule could provide a method, say `NewTransport(delegate http.RoundTripper, options ...Something) http.RoundTripper` or similar, that adds whatever security a client wants to each request.  Client code can then inject that into any `http.Client`.

This is all similar to what `justinas/alice` does on the serverside.  The `httpaux` library, at https://github.com/xmidt-org/httpaux/tree/main/roundtrip, provides a framework for decorating round trippers in a manner very similar to alice.
