### ISSUE TITLE
Add Options for MetricValidator

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/bascule#87]
https://github.com/xmidt-org/bascule/blob/d160adf49419cd2ff4bb453c130cdd3950f2b774/basculechecks/metrics.go#L104

Some Option ideas:
- `WithEndpoints([]*regexp.Regexp)` - if not provided, an empty string (would cause `CapabilitiesMap` to error out every time; not ideal) or `n/a` could be used instead of `not_recognized`.  Then someone testing would be able to determine if the label value is a configuration/setup issue.  This could also be providing a function that determines the endpoint label to use given the url in the request.
- `MonitorOnly()` - `errorOut` should be `true` by default.  If this option is provided, it will be `false`.

An added benefit of having a `NewMetricValidator` function is it allows us to nil check the measures and `CapabilitiesChecker`.

**Comment by joe94** [comment]
Sounds good to me 👍 
The part about a default label value for endpoints reminded me that we could improve readability in this function by having it return a struct with the different label values as fields. https://github.com/xmidt-org/bascule/blob/d160adf49419cd2ff4bb453c130cdd3950f2b774/basculechecks/metricvalidator.go#L118 

This could be part of this issue or be on its own.
